# Generated by Django 3.0.3 on 2020-04-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200304_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='DEFAULT TITLE', max_length=500),
        ),
    ]
